### ISSUE TITLE
Any plans to support customizing `option` tags?

### ISSUE THREAD

**Issue by pedrokost** [thefrontside/ember-cli-select#1]
I would like to customize the templates of `custom-option` -- however, the `<select>` tag cannot hold images and other non-textual elements.

I assume this would require manually handling the show/hide logic of the options instead of relying on the default browser behavior.

Is this something you would be interested in adding?

**Comment by cowboyd** [comment]
@pedrokost This library is meant to be a no-nonsense way to use native html selects elements.

For a re-implementation with lots of fun features, see http://emberui.com/documentation/select

Also note, this project has been deprecated in favor of [thefrontside/emberx-select](/thefrontside/emberx-select)
